SET SERVEROUT ON;

CREATE OR REPLACE PROCEDURE PROC_EXCEPTION IS

    MINHAEXE EXCEPTION;
    N        NUMBER := 10;
    
BEGIN
    FOR I IN &I .. &N LOOP
    DBMS_OUTPUT.PUT_LINE(I * I);
    IF I * 2 = 10 THEN
    RAISE MINHAEXE;
    
    END IF;
    END LOOP;
    
EXCEPTION
    WHEN MINHAEXE THEN
    RAISE_APPLICATION_ERROR(-20015, 'VOCE CAIU NA EXCECAO');
END PROC_EXCEPTION;

EXEC PROC_EXCEPTION();